// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: files.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
  account_id,
  filename,
  filepath
) VALUES (
  $1, $2, $3
)
RETURNING id, account_id, filename, filepath, created_at
`

type CreateFileParams struct {
	AccountID int64  `json:"account_id"`
	Filename  string `json:"filename"`
	Filepath  string `json:"filepath"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile, arg.AccountID, arg.Filename, arg.Filepath)
	var i File
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Filename,
		&i.Filepath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE filename = $1 and account_id = $2
`

type DeleteFileParams struct {
	Filename  string `json:"filename"`
	AccountID int64  `json:"account_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.Filename, arg.AccountID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, account_id, filename, filepath, created_at FROM files
WHERE filename = $1 and account_id = $2 LIMIT 1
`

type GetFileParams struct {
	Filename  string `json:"filename"`
	AccountID int64  `json:"account_id"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.Filename, arg.AccountID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Filename,
		&i.Filepath,
		&i.CreatedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, account_id, filename, filepath, created_at FROM files
WHERE account_id = $1 
ORDER BY filename
`

func (q *Queries) ListFiles(ctx context.Context, accountID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Filename,
			&i.Filepath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilePath = `-- name: UpdateFilePath :exec
UPDATE files
  set filepath = $3
WHERE filename = $1 and account_id = $2
`

type UpdateFilePathParams struct {
	Filename  string `json:"filename"`
	AccountID int64  `json:"account_id"`
	Filepath  string `json:"filepath"`
}

func (q *Queries) UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) error {
	_, err := q.db.ExecContext(ctx, updateFilePath, arg.Filename, arg.AccountID, arg.Filepath)
	return err
}
