// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Passhash  string    `json:"passhash"`
	Blocked   bool      `json:"blocked"`
	CreatedAt time.Time `json:"created_at"`
}

type File struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
	Filename  string `json:"filename"`
	Filepath  string `json:"filepath"`
	// file ready or not for listing
	Ready     bool      `json:"ready"`
	CreatedAt time.Time `json:"created_at"`
}

type FilesMetadatum struct {
	ID        int64     `json:"id"`
	FileID    int64     `json:"file_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type Secret struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type SecretsMetadatum struct {
	ID        int64     `json:"id"`
	SecretID  int64     `json:"secret_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}
