// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Passhash  string    `json:"passhash"`
	Blocked   bool      `json:"blocked"`
	CreatedAt time.Time `json:"created_at"`
}

type File struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Filename  string    `json:"filename"`
	Filepath  string    `json:"filepath"`
	Filesize  int64     `json:"filesize"`
	Deleted   bool      `json:"deleted"`
	CreatedAt time.Time `json:"created_at"`
}

type Metadatum struct {
	ID        int64         `json:"id"`
	SecretID  sql.NullInt64 `json:"secret_id"`
	FileID    sql.NullInt64 `json:"file_id"`
	Key       string        `json:"key"`
	Value     string        `json:"value"`
	CreatedAt time.Time     `json:"created_at"`
}

type Secret struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}
