// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	BlockAccount(ctx context.Context, username string) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFileMetadata(ctx context.Context, arg CreateFileMetadataParams) (FilesMetadatum, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateSecretMetadata(ctx context.Context, arg CreateSecretMetadataParams) (SecretsMetadatum, error)
	DeleteAccount(ctx context.Context, username string) error
	DeleteFile(ctx context.Context, arg DeleteFileParams) error
	DeleteFileMetadata(ctx context.Context, arg DeleteFileMetadataParams) error
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) error
	DeleteSecretMetadata(ctx context.Context, arg DeleteSecretMetadataParams) error
	GetAccount(ctx context.Context, username string) (Account, error)
	GetFile(ctx context.Context, arg GetFileParams) (File, error)
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	ListFileMetadata(ctx context.Context, fileID int64) ([]FilesMetadatum, error)
	ListFiles(ctx context.Context, accountID int64) ([]File, error)
	ListSecretMetadata(ctx context.Context, secretID int64) ([]SecretsMetadatum, error)
	ListSecrets(ctx context.Context, accountID int64) ([]Secret, error)
	MarkFileReady(ctx context.Context, arg MarkFileReadyParams) error
	UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error
	UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) error
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) error
	UpdateSecretMetadata(ctx context.Context, arg UpdateSecretMetadataParams) error
}

var _ Querier = (*Queries)(nil)
