// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	BlockAccount(ctx context.Context, username string) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateSecretMetadata(ctx context.Context, arg CreateSecretMetadataParams) (Metadatum, error)
	DeleteAccount(ctx context.Context, username string) error
	DeleteAllSecretMetadata(ctx context.Context, arg DeleteAllSecretMetadataParams) error
	DeleteFile(ctx context.Context, arg DeleteFileParams) error
	DeleteOneSecretMetadata(ctx context.Context, arg DeleteOneSecretMetadataParams) error
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) error
	DeletedFileById(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, username string) (Account, error)
	GetDeletedFiles(ctx context.Context) ([]GetDeletedFilesRow, error)
	GetFile(ctx context.Context, arg GetFileParams) (File, error)
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	ListFiles(ctx context.Context, accountID int64) ([]File, error)
	ListSecretMetadata(ctx context.Context, arg ListSecretMetadataParams) ([]Metadatum, error)
	ListSecrets(ctx context.Context, accountID int64) ([]Secret, error)
	UpdateFileName(ctx context.Context, arg UpdateFileNameParams) error
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) error
	UpdateSecretMetadata(ctx context.Context, arg UpdateSecretMetadataParams) error
}

var _ Querier = (*Queries)(nil)
